name: Colcon build and test

on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build_and_test:
    name: build_and_test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@0.1.3
      - uses: ros-tooling/action-ros-ci@v0.2
        id: action_ros_ci_step
        with:
          package-name: 
            rexrov2_description
          target-ros2-distro: foxy
          vcs-repo-file-url: ""
      - uses: actions/upload-artifact@v1
        with:
          if: failure() # upload the logs even when the build fails
          name: colcon-logs
          path: ${{ steps.action_ros_ci_step.outputs.ros-workspace-directory-name }}/build/rexrov2_description/test_results/rexrov2_description
