name: ament_lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    strategy:
      fail-fast: false
      matrix:
          linter: [xmllint, copyright, lint_cmake, cpplint, cppcheck, uncrustify, flake8, pep257]
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@0.1.4
      - uses: ros-tooling/action-ros-lint@0.1.3
        with:
          linter: ${{ matrix.linter }}
          package-name: rexrov2