name: ros-ci
on: [pull_request]
jobs:
  build:
    name: build and test
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:focal
    steps:
      - uses: ros-tooling/setup-ros@0.2.1
      - uses: ros-tooling/action-ros-ci@0.2.1
        with:
          package-name: 
            rexrov2
            rexrov2_description
          target-ros2-distro: foxy
