name: ament_lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:focal
    strategy:
      fail-fast: false
      matrix:
          linter: [copyright, flake8, pep257, xmllint]
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@0.2.1
      - uses: ros-tooling/action-ros-lint@0.1.3
        with:
          linter: ${{ matrix.linter }}
          package-name: 
            rexrov2
            rexrov2_description
