name: Ament Lint

on: [pull_request]

jobs:
  ament_lint:
    name: ament_lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
          linter: [xmllint, lint_cmake, flake8, copyright, pep257]
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@0.1.3
      - uses: ros-tooling/action-ros-lint@master
        with:
          distribution: foxy
          linter: ${{ matrix.linter }}
          package-name:
            rexrov2_description
